(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["sites_professional$45profile$45web_work$45history"],{

/***/ "./src/node_modules/crossfade.js":
/*!***************************************!*\
  !*** ./src/node_modules/crossfade.js ***!
  \***************************************/
/*! exports provided: send, receive */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "send", function() { return send; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "receive", function() { return receive; });
/* harmony import */ var svelte_easing__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/easing */ "./node_modules/svelte/easing/index.mjs");
/* harmony import */ var svelte_transition__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte/transition */ "./node_modules/svelte/transition/index.mjs");


const [send, receive] = Object(svelte_transition__WEBPACK_IMPORTED_MODULE_1__["crossfade"])({
  easing: svelte_easing__WEBPACK_IMPORTED_MODULE_0__["quintInOut"],
  duration: d => Math.sqrt(d*1200),
  fallback(node, params) {
    const style = getComputedStyle(node);
    const transform = style.transform === "none" ? "" : style.transform;

    return {
      duration: 1200,
      easing: svelte_easing__WEBPACK_IMPORTED_MODULE_0__["quintOut"],
      css: t => `
                transform: ${transform};
                opacity: ${t}
            `
    };
  }
});




/***/ }),

/***/ "./src/routes/sites/professional-profile-web/work-history.svelte":
/*!***********************************************************************!*\
  !*** ./src/routes/sites/professional-profile-web/work-history.svelte ***!
  \***********************************************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var crossfade__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! crossfade */ "./src/node_modules/crossfade.js");
/* src/routes/sites/professional-profile-web/work-history.svelte generated by Svelte v3.8.0 */



const file = "src/routes/sites/professional-profile-web/work-history.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-11i1ky9-style';
	style.textContent = "body{background:rgb(190, 190, 241);color:white;max-height:1200px;overflow:hidden}svg.svelte-11i1ky9{stroke:white}.ring.svelte-11i1ky9,.ring1.svelte-11i1ky9{opacity:.2;position:absolute;top:-80px;left:-80px;padding:0;margin:0}.top-circle.svelte-11i1ky9{position:absolute;width:1200px;height:1200px;left:-300px;top:-700px;background-image:url('blueball.svg');z-index:-1}.top-dashed.svelte-11i1ky9{padding:0;margin:0;position:absolute;transform:scale(.74,.74);width:1960px;height:2000px;left:-610px;top:-1050px;animation-name:svelte-11i1ky9-spinScale;animation-duration:20000ms;animation-iteration-count:infinite;animation-timing-function:linear;background-image:url('dashedcircle.svg');opacity:.1;z-index:-2}.bottom-dashed.svelte-11i1ky9{padding:0;margin:0;position:absolute;transform:scale(.7,.7);width:1960px;height:2000px;left:-10px;top:50px;animation-name:svelte-11i1ky9-spinScale2;animation-duration:20000ms;animation-iteration-count:infinite;animation-timing-function:linear;background-image:url('dashedcircle.svg');opacity:.35;z-index:-2}.bottom-circle.svelte-11i1ky9{position:absolute;width:1200px;height:2000px;left:300px;top:300px;background-image:url('blueball.svg');z-index:-1}.background-container.svelte-11i1ky9{position:relative}.ring.svelte-11i1ky9{transition:all 0.3s ease-in-out;animation-name:svelte-11i1ky9-spin;animation-duration:5000ms;animation-iteration-count:infinite;animation-timing-function:linear}.ring1.svelte-11i1ky9{transition:all 0.3s ease-in-out;animation-name:svelte-11i1ky9-spin-re;animation-duration:5000ms;animation-iteration-count:infinite;animation-timing-function:linear}a.svelte-11i1ky9{color:rgb(255, 255, 255);font-size:29px;transition:all .6s ease-in-out}.list-eyebrow.svelte-11i1ky9{color:rgba(0, 0, 0, 0.753)}.nav-list.svelte-11i1ky9{padding:10px;margin-top:20px}.nav-list.svelte-11i1ky9>ul.svelte-11i1ky9{list-style:none;padding:0;width:100%;margin:0 auto}ul.svelte-11i1ky9:hover>li>a.svelte-11i1ky9{color:rgb(244, 176, 250);width:100%}.nav-list.svelte-11i1ky9>ul>li.svelte-11i1ky9{padding:15px 0;font-size:24px;width:100%;margin:0 auto;text-align:center;transition:all .6s ease-in-out}.nav-list.svelte-11i1ky9>ul>li.svelte-11i1ky9:hover{border-radius:45px 0px 45px 0px;background:rgba(255, 255, 255, 0.235);margin:0 auto;box-shadow:0 0 0 0 black;color:rgb(70, 70, 70) !important;font-size:29px}.nav-list.svelte-11i1ky9>ul>li.svelte-11i1ky9:nth-child(even):hover{border-radius:0px 45px 0px 45px;background:rgba(255, 255, 255, 0.235);margin:0 auto;box-shadow:0 0 0 0 black;color:rgb(70, 70, 70) !important;font-size:29px}.nav-list.svelte-11i1ky9>ul>li.svelte-11i1ky9:last-child:hover{border-radius:0px 0px 45px 45px;background:rgba(255, 255, 255, 0.235);margin:0 auto;box-shadow:0 0 0 0 black;color:rgb(70, 70, 70) !important;font-size:29px}.nav-list.svelte-11i1ky9>ul>li.svelte-11i1ky9:first-child:hover{border-radius:45px 45px 0px 0px;background:rgba(255, 255, 255, 0.235);margin:0 auto;box-shadow:0 0 0 0 black;color:rgb(70, 70, 70) !important;font-size:29px}.nav-list.svelte-11i1ky9>ul>li:hover>a.svelte-11i1ky9{color:rgb(255, 228, 242);text-decoration:none}.intro-container.svelte-11i1ky9{border-radius:30px;box-shadow:0 0 12px 3px rgba(0, 0, 0, 0.324);display:flex;flex-direction:column;width:90%;margin:60px auto;background:rgba(139, 129, 228, 0.845);padding-bottom:20px;opacity:1}@media screen and (min-width:768px){.intro-container.svelte-11i1ky9{width:80%;background:rgb(139, 129, 228)}}.img-wrapper.svelte-11i1ky9{position:relative;max-width:100%;margin:0 auto;transform:translate(0,-30px)}img.svelte-11i1ky9{max-width:100%}.profile-img.svelte-11i1ky9{border-radius:50%;box-shadow:0 0 12px 3px black}h1.svelte-11i1ky9,h2.svelte-11i1ky9{text-align:center}h1.svelte-11i1ky9{font-size:30px;padding:0;margin:0}h2.svelte-11i1ky9{font-size:19px}@keyframes svelte-11i1ky9-spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}@keyframes svelte-11i1ky9-spinScale{from{transform:rotate(0deg) scale(.74,.74)}to{transform:rotate(360deg) scale(.74,.74)}}@keyframes svelte-11i1ky9-spinScale2{from{transform:rotate(0deg) scale(.84,.84)}to{transform:rotate(360deg) scale(.84,.84)}}@keyframes svelte-11i1ky9-spin-re{from{transform:rotate(0deg)}to{transform:rotate(-360deg)}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoid29yay1oaXN0b3J5LnN2ZWx0ZSIsInNvdXJjZXMiOlsid29yay1oaXN0b3J5LnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuICAgIGltcG9ydCB7IHNlbmQsIHJlY2VpdmUgfSBmcm9tIFwiY3Jvc3NmYWRlXCI7XG4gIDwvc2NyaXB0PlxuICBcbiAgICA8IS0tIDxoMSBjbGFzcz1cInVuaXR5LWJvZHlcIiBvdXQ6c2VuZD1cInt7a2V5OiAndGl0bGUtYm9keSd9fVwiIGluOnJlY2VpdmU9XCJ7e2tleTogJ3RpdGxlLWJvZHknfX1cIj5cbiAgICAgICAgdW5pdHkgZ28gaGVyZVxuICAgIDwvaDE+IC0tPlxuXG48ZGl2IGNsYXNzPVwiYmFja2dyb3VuZC1jb250YWluZXJcIj5cbiAgICA8ZGl2IGNsYXNzPVwidG9wLWNpcmNsZVwiPjwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJ0b3AtZGFzaGVkXCI+PC9kaXY+XG5cbiAgICA8ZGl2IGNsYXNzPVwiYm90dG9tLWNpcmNsZVwiPjwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJib3R0b20tZGFzaGVkXCI+PC9kaXY+XG48L2Rpdj5cbjxkaXYgY2xhc3M9XCJpbnRyby1jb250YWluZXJcIj5cbiAgICA8ZGl2IGNsYXNzPVwiaW1nLXdyYXBwZXJcIj5cbiAgICAgICAgPGltZyBzcmM9XCJwcm9maWxlLmpwZWdcIiBjbGFzcz1cInByb2ZpbGUtaW1nXCIgYWx0PVwiTGV2eSBBbnRob255IEFkYW1zIFByb2ZpbGUgUGljdHVyZVwiPlxuXG4gICAgICAgIDxzdmdcbiAgICAgICAgY2xhc3M9XCJyaW5nXCJcbiAgICAgICAgd2lkdGg9XCIzMjBweFwiXG4gICAgICAgIGhlaWdodD1cIjMyMHB4XCJcbiAgICAgICAgdmVyc2lvbj1cIjEuMVwidmlld0JveD1cIjAgMCAyMTAgMjk3XCJ4bWxucz1cImh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnXCJ4bWxuczpjYz1cImh0dHA6Ly9jcmVhdGl2ZWNvbW1vbnMub3JnL25zI1wieG1sbnM6ZGM9XCJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xL1wieG1sbnM6b3NiPVwiaHR0cDovL3d3dy5vcGVuc3dhdGNoYm9vay5vcmcvdXJpLzIwMDkvb3NiXCJ4bWxuczpyZGY9XCJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjXCI+XG4gICAgICAgIDxwYXRoIGQ9XCJtMTg1LjAzIDE0Ny4wM2MwLjI5MzYyIDI4LjQ5MS0xNy42NzcgNTUuNDIyLTQyLjk2OSA2Ny45MjktMzAuNzMyIDE2LjA1Mi03MS4xMDcgMTEuMTYtOTYuNjAxLTEyLjUzLTIwLjM0LTE4LjEwNS0yOS43NzktNDcuNzQ5LTIyLjQyMy03NC4xMzEgNy41MDA1LTI5LjIwOCAzMy42NDMtNTEuNTQzIDYyLjk2Mi01Ni45NDMgMzIuMTU1LTYuNjU2NSA2OC4wMjEgNi43NDEgODYuMzE1IDM0LjM3NSA4LjE4NDMgMTIuMTE5IDEyLjc0NyAyNi42NiAxMi43MTYgNDEuM3pcIiBmaWxsPVwibm9uZVwiIHN0cm9rZS13aWR0aD1cIjEuODQyOFwiIC8+XG4gICAgICAgIDxwYXRoIGQ9XCJtNjMuNSA4OC40NDZjMC4zMjg2OCA4LjQ3NDYtOS4wODA1IDE1LjIwOS0xNi45OTYgMTIuMTY0LTguMTI3Ni0yLjQyMjItMTEuNDY3LTEzLjUtNi4wMzI3LTIwLjAxMSA0LjkxNDEtNi45MTIxIDE2LjQ3Ny02LjUwMDMgMjAuODg3IDAuNzQzNzggMS4zOTA4IDIuMDg5NCAyLjE0NTYgNC41OTI5IDIuMTQxMyA3LjEwMjl6XCIgc3Ryb2tlLXdpZHRoPVwiM1wiIC8+XG4gICAgICAgIDwvc3ZnPlxuXG4gICAgICAgIDxzdmdcbiAgICAgICAgY2xhc3M9XCJyaW5nMVwiXG4gICAgICAgIHdpZHRoPVwiMzIwcHhcIlxuICAgICAgICBoZWlnaHQ9XCIzMjBweFwiXG4gICAgICAgIHZlcnNpb249XCIxLjFcInZpZXdCb3g9XCIwIDAgMjEwIDI5N1wieG1sbnM9XCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wieG1sbnM6Y2M9XCJodHRwOi8vY3JlYXRpdmVjb21tb25zLm9yZy9ucyNcInhtbG5zOmRjPVwiaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS9cInhtbG5zOm9zYj1cImh0dHA6Ly93d3cub3BlbnN3YXRjaGJvb2sub3JnL3VyaS8yMDA5L29zYlwieG1sbnM6cmRmPVwiaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zI1wiPlxuICAgICAgICA8cGF0aCB0cmFuc2Zvcm09XCJtYXRyaXgoLjM1Mjg5IDAgMCAuMzM1OTIgLTgzLjIxNSAtOTguNjcpXCJkPVwibTUyNi44MSA1MDEuMjlhMjMyLjk5IDIzMC4xNCAwIDAgMC0xMTguNjkgMzIuMjk1IDM2LjQxNyAzOC4yNTYgMCAwIDEgNy42MzI4IDIzLjQzNiAzNi40MTcgMzguMjU2IDAgMCAxLTM2LjQxNiAzOC4yNTggMzYuNDE3IDM4LjI1NiAwIDAgMS0yOC40NDMtMTQuMzY5IDIzMi45OSAyMzAuMTQgMCAwIDAtNTYuNzQgMTUwLjUyIDIzMi45OSAyMzAuMTQgMCAwIDAgMjMyLjk5IDIzMC4xNCAyMzIuOTkgMjMwLjE0IDAgMCAwIDIzMi45OS0yMzAuMTQgMjMyLjk5IDIzMC4xNCAwIDAgMC0yMzIuOTktMjMwLjEzIDIzMi45OSAyMzAuMTQgMCAwIDAtMC4zMzU5NCAwem0tMTc1LjkyIDc5LjYxOWEyMzIuOTkgMjMwLjE0IDAgMCAxIDU3LjIyNy00Ny4zMjQgMzYuNDE3IDM4LjI1NiAwIDAgMC0yOC43ODMtMTQuODIgMzYuNDE3IDM4LjI1NiAwIDAgMC0zNi40MTggMzguMjU2IDM2LjQxNyAzOC4yNTYgMCAwIDAgNy45NzQ2IDIzLjg4OXpcImZpbGw9XCJub25lXCJzdHJva2Utd2lkdGg9XCI1LjM1MjNcIiAvPlxuICAgICAgICA8L3N2Zz5cblxuICAgIDwvZGl2PlxuICBcbjxoMSBzdHlsZT0ncGFkZGluZzoxMHB4Jz5MZXZ5IEFudGhvbnkgQWRhbXM8L2gxPlxuPGgyPkludGVyYWN0aXZlIFdlYiBEZXZlbG9wZXI8L2gyPlxuXG48aDIgY2xhc3M9XCJsaXN0LWV5ZWJyb3dcIiBzdHlsZT1cIm1hcmdpbi10b3A6NDBweDtmb250LXNpemU6MTRweDtcIj5QbGVhc2UgQ2hvb3NlIGJlbG93PC9oMj5cblxuPG5hdiByb2xlPVwibmF2aWdhdGlvblwiIGNsYXNzPVwibmF2LWxpc3RcIj5cbiAgICA8dWw+XG4gICAgICAgIDxsaT48YSBocmVmPVwiXCI+V29yayBIaXN0b3J5PC9hPjwvbGk+XG4gICAgICAgIDxsaT48YSBocmVmPVwiXCI+U2tpbGxzPC9hPjwvbGk+XG4gICAgICAgIDxsaT48YSBocmVmPVwiXCI+UHJvamVjdHM8L2E+PC9saT5cbiAgICAgICAgPGxpPjxhIGhyZWY9XCJcIj5Db250YWN0PC9hPjwvbGk+XG4gICAgPC91bD5cbjwvbmF2PlxuPC9kaXY+XG5cblxuPHN0eWxlPlxuICAgIDpnbG9iYWwoYm9keSl7XG4gICAgICAgIGJhY2tncm91bmQ6cmdiKDE5MCwgMTkwLCAyNDEpO1xuICAgICAgICBjb2xvcjogd2hpdGU7XG4gICAgICAgIG1heC1oZWlnaHQ6MTIwMHB4O1xuICAgICAgICBvdmVyZmxvdzpoaWRkZW47XG4gICAgfVxuICAgIHN2Z3tcbiAgICAgICAgc3Ryb2tlOndoaXRlO1xuICAgIH1cbiAgICAucmluZywucmluZzF7XG4gICAgICAgIG9wYWNpdHk6IC4yO1xuICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gICAgICAgIHRvcDotODBweDtcbiAgICAgICAgbGVmdDotODBweDtcbiAgICAgICAgcGFkZGluZzowO1xuICAgICAgICBtYXJnaW46MDtcbiAgICB9XG4gICAgLnRvcC1jaXJjbGV7XG4gICAgICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgICAgICAgd2lkdGg6MTIwMHB4O1xuICAgICAgICBoZWlnaHQ6MTIwMHB4O1xuICAgICAgICBsZWZ0Oi0zMDBweDtcbiAgICAgICAgdG9wOi03MDBweDtcbiAgICAgICAgYmFja2dyb3VuZC1pbWFnZTogdXJsKCdibHVlYmFsbC5zdmcnKTtcbiAgICAgICAgei1pbmRleDogLTE7XG4gICAgfVxuICAgIC50b3AtZGFzaGVke1xuICAgICAgICBwYWRkaW5nOjA7XG4gICAgICAgIG1hcmdpbjowO1xuICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gICAgICAgIHRyYW5zZm9ybTogc2NhbGUoLjc0LC43NCk7XG4gICAgICAgIHdpZHRoOjE5NjBweDtcbiAgICAgICAgaGVpZ2h0OjIwMDBweDtcbiAgICAgICAgbGVmdDotNjEwcHg7XG4gICAgICAgIHRvcDotMTA1MHB4O1xuICAgICAgICBhbmltYXRpb24tbmFtZTogc3BpblNjYWxlO1xuICAgICAgICBhbmltYXRpb24tZHVyYXRpb246IDIwMDAwbXM7XG4gICAgICAgIGFuaW1hdGlvbi1pdGVyYXRpb24tY291bnQ6IGluZmluaXRlO1xuICAgICAgICBhbmltYXRpb24tdGltaW5nLWZ1bmN0aW9uOiBsaW5lYXI7XG4gICAgICAgIGJhY2tncm91bmQtaW1hZ2U6IHVybCgnZGFzaGVkY2lyY2xlLnN2ZycpO1xuICAgICAgICBvcGFjaXR5OiAuMTtcbiAgICAgICAgei1pbmRleDogLTI7XG4gICAgfVxuICAgIC5ib3R0b20tZGFzaGVke1xuICAgICAgICBwYWRkaW5nOjA7XG4gICAgICAgIG1hcmdpbjowO1xuICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gICAgICAgIHRyYW5zZm9ybTogc2NhbGUoLjcsLjcpO1xuICAgICAgICB3aWR0aDoxOTYwcHg7XG4gICAgICAgIGhlaWdodDoyMDAwcHg7XG4gICAgICAgIGxlZnQ6LTEwcHg7XG4gICAgICAgIHRvcDo1MHB4O1xuICAgICAgICBhbmltYXRpb24tbmFtZTogc3BpblNjYWxlMjtcbiAgICAgICAgYW5pbWF0aW9uLWR1cmF0aW9uOiAyMDAwMG1zO1xuICAgICAgICBhbmltYXRpb24taXRlcmF0aW9uLWNvdW50OiBpbmZpbml0ZTtcbiAgICAgICAgYW5pbWF0aW9uLXRpbWluZy1mdW5jdGlvbjogbGluZWFyO1xuICAgICAgICBiYWNrZ3JvdW5kLWltYWdlOiB1cmwoJ2Rhc2hlZGNpcmNsZS5zdmcnKTtcbiAgICAgICAgb3BhY2l0eTogLjM1O1xuICAgICAgICB6LWluZGV4OiAtMjtcbiAgICB9XG4gICAgLmJvdHRvbS1jaXJjbGV7XG4gICAgICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgICAgICAgd2lkdGg6MTIwMHB4O1xuICAgICAgICBoZWlnaHQ6MjAwMHB4O1xuICAgICAgICBsZWZ0OjMwMHB4O1xuICAgICAgICB0b3A6MzAwcHg7XG4gICAgICAgIGJhY2tncm91bmQtaW1hZ2U6IHVybCgnYmx1ZWJhbGwuc3ZnJyk7XG4gICAgICAgIHotaW5kZXg6IC0xO1xuICAgIH1cbiAgICAuYmFja2dyb3VuZC1jb250YWluZXJ7XG4gICAgICAgIHBvc2l0aW9uOiByZWxhdGl2ZTtcbiAgICB9XG4gICAgLmJnLXJpbmd7XG4gICAgICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgICAgICAgei1pbmRleDogMTtcbiAgICAgICAgb3BhY2l0eTogLjU7XG4gICAgfVxuICAgIC5yaW5ne1xuICAgICAgICB0cmFuc2l0aW9uOiBhbGwgMC4zcyBlYXNlLWluLW91dDtcbiAgICAgICAgYW5pbWF0aW9uLW5hbWU6IHNwaW47XG4gICAgICAgIGFuaW1hdGlvbi1kdXJhdGlvbjogNTAwMG1zO1xuICAgICAgICBhbmltYXRpb24taXRlcmF0aW9uLWNvdW50OiBpbmZpbml0ZTtcbiAgICAgICAgYW5pbWF0aW9uLXRpbWluZy1mdW5jdGlvbjogbGluZWFyO1xuICAgIH1cbiAgICAucmluZzF7XG4gICAgICAgIHRyYW5zaXRpb246IGFsbCAwLjNzIGVhc2UtaW4tb3V0O1xuICAgICAgICBhbmltYXRpb24tbmFtZTogc3Bpbi1yZTtcbiAgICAgICAgYW5pbWF0aW9uLWR1cmF0aW9uOiA1MDAwbXM7XG4gICAgICAgIGFuaW1hdGlvbi1pdGVyYXRpb24tY291bnQ6IGluZmluaXRlO1xuICAgICAgICBhbmltYXRpb24tdGltaW5nLWZ1bmN0aW9uOiBsaW5lYXI7XG4gICAgfVxuICAgIGF7XG4gICAgICAgIGNvbG9yOnJnYigyNTUsIDI1NSwgMjU1KTtcbiAgICAgICAgZm9udC1zaXplOjI5cHg7XG4gICAgICAgIHRyYW5zaXRpb246YWxsIC42cyBlYXNlLWluLW91dDtcbiAgICB9XG4gICAgLmxpc3QtZXllYnJvd3tcbiAgICAgICAgY29sb3I6cmdiYSgwLCAwLCAwLCAwLjc1Myk7XG4gICAgfVxuICAgIC5uYXYtbGlzdHtcbiAgICAgICAgcGFkZGluZzoxMHB4O1xuICAgICAgICBtYXJnaW4tdG9wOjIwcHg7XG4gICAgfVxuICAgIC5uYXYtbGlzdD51bHtcbiAgICAgICAgbGlzdC1zdHlsZTogbm9uZTtcbiAgICAgICAgcGFkZGluZzowO1xuICAgICAgICB3aWR0aDoxMDAlO1xuICAgICAgICBtYXJnaW46MCBhdXRvO1xuICAgIH1cbiAgICB1bDpob3Zlcj5saT5he1xuICAgICAgICBjb2xvcjpyZ2IoMjQ0LCAxNzYsIDI1MCk7XG4gICAgICAgIHdpZHRoOjEwMCU7XG4gICAgfVxuICAgIC5uYXYtbGlzdD51bD5saXtcbiAgICAgICAgcGFkZGluZzoxNXB4IDA7XG4gICAgICAgIGZvbnQtc2l6ZToyNHB4O1xuICAgICAgICB3aWR0aDoxMDAlO1xuICAgICAgICBtYXJnaW46MCBhdXRvO1xuICAgICAgICB0ZXh0LWFsaWduOmNlbnRlcjtcbiAgICAgICAgdHJhbnNpdGlvbjphbGwgLjZzIGVhc2UtaW4tb3V0O1xuICAgIH1cbiAgICBcbiAgICAubmF2LWxpc3Q+dWw+bGk6aG92ZXJ7XG4gICAgICAgIGJvcmRlci1yYWRpdXM6NDVweCAwcHggNDVweCAwcHg7XG4gICAgICAgIGJhY2tncm91bmQ6cmdiYSgyNTUsIDI1NSwgMjU1LCAwLjIzNSk7XG4gICAgICAgIG1hcmdpbjowIGF1dG87XG4gICAgICAgIGJveC1zaGFkb3c6MCAwIDAgMCBibGFjaztcbiAgICAgICAgY29sb3I6cmdiKDcwLCA3MCwgNzApICFpbXBvcnRhbnQ7XG4gICAgICAgIGZvbnQtc2l6ZToyOXB4O1xuICAgIH1cbiAgICAubmF2LWxpc3Q+dWw+bGk6bnRoLWNoaWxkKGV2ZW4pOmhvdmVye1xuICAgICAgICBib3JkZXItcmFkaXVzOjBweCA0NXB4IDBweCA0NXB4O1xuICAgICAgICBiYWNrZ3JvdW5kOnJnYmEoMjU1LCAyNTUsIDI1NSwgMC4yMzUpO1xuICAgICAgICBtYXJnaW46MCBhdXRvO1xuICAgICAgICBib3gtc2hhZG93OjAgMCAwIDAgYmxhY2s7XG4gICAgICAgIGNvbG9yOnJnYig3MCwgNzAsIDcwKSAhaW1wb3J0YW50O1xuICAgICAgICBmb250LXNpemU6MjlweDtcbiAgICB9XG4gICAgLm5hdi1saXN0PnVsPmxpOmxhc3QtY2hpbGQ6aG92ZXJ7XG4gICAgICAgIGJvcmRlci1yYWRpdXM6MHB4IDBweCA0NXB4IDQ1cHg7XG4gICAgICAgIGJhY2tncm91bmQ6cmdiYSgyNTUsIDI1NSwgMjU1LCAwLjIzNSk7XG4gICAgICAgIG1hcmdpbjowIGF1dG87XG4gICAgICAgIGJveC1zaGFkb3c6MCAwIDAgMCBibGFjaztcbiAgICAgICAgY29sb3I6cmdiKDcwLCA3MCwgNzApICFpbXBvcnRhbnQ7XG4gICAgICAgIGZvbnQtc2l6ZToyOXB4O1xuICAgIH1cbiAgICAubmF2LWxpc3Q+dWw+bGk6Zmlyc3QtY2hpbGQ6aG92ZXJ7XG4gICAgICAgIGJvcmRlci1yYWRpdXM6NDVweCA0NXB4IDBweCAwcHg7XG4gICAgICAgIGJhY2tncm91bmQ6cmdiYSgyNTUsIDI1NSwgMjU1LCAwLjIzNSk7XG4gICAgICAgIG1hcmdpbjowIGF1dG87XG4gICAgICAgIGJveC1zaGFkb3c6MCAwIDAgMCBibGFjaztcbiAgICAgICAgY29sb3I6cmdiKDcwLCA3MCwgNzApICFpbXBvcnRhbnQ7XG4gICAgICAgIGZvbnQtc2l6ZToyOXB4O1xuICAgIH1cblxuICAgIC5uYXYtbGlzdD51bD5saTpob3Zlcj5he1xuICAgICAgICBjb2xvcjpyZ2IoMjU1LCAyMjgsIDI0Mik7XG4gICAgICAgIHRleHQtZGVjb3JhdGlvbjogbm9uZTtcblxuICAgIH1cbiAgICAuaW50cm8tY29udGFpbmVye1xuICAgICAgICBib3JkZXItcmFkaXVzOjMwcHg7XG4gICAgICAgIGJveC1zaGFkb3c6IDAgMCAxMnB4IDNweCByZ2JhKDAsIDAsIDAsIDAuMzI0KTtcbiAgICAgICAgZGlzcGxheTogZmxleDtcbiAgICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcbiAgICAgICAgd2lkdGg6OTAlO1xuICAgICAgICBtYXJnaW46NjBweCBhdXRvO1xuICAgICAgICBiYWNrZ3JvdW5kOnJnYmEoMTM5LCAxMjksIDIyOCwgMC44NDUpO1xuXG4gICAgICAgIHBhZGRpbmctYm90dG9tOjIwcHg7XG4gICAgICAgIG9wYWNpdHk6IDE7XG4gICAgICAgIFxuICAgIH1cbiAgICBAbWVkaWEgc2NyZWVuIGFuZCAobWluLXdpZHRoOjc2OHB4KXtcbiAgICAgICAgLmludHJvLWNvbnRhaW5lcntcbiAgICAgICAgICAgIHdpZHRoOjgwJTtcbiAgICAgICAgICAgIGJhY2tncm91bmQ6cmdiKDEzOSwgMTI5LCAyMjgpO1xuICAgICAgICB9XG4gICAgfVxuXG4gICAgLmltZy13cmFwcGVye1xuICAgICAgICBwb3NpdGlvbjogcmVsYXRpdmU7XG4gICAgICAgIG1heC13aWR0aDoxMDAlO1xuICAgICAgICBtYXJnaW46MCBhdXRvO1xuICAgICAgICB0cmFuc2Zvcm06dHJhbnNsYXRlKDAsLTMwcHgpO1xuICAgIH1cbiAgICBpbWd7XG4gICAgICAgIG1heC13aWR0aDogMTAwJTtcbiAgICAgICAgfVxuICAgICAgICAucHJvZmlsZS1pbWd7XG4gICAgICAgICAgICBib3JkZXItcmFkaXVzOjUwJTtcbiAgICAgICAgICAgIGJveC1zaGFkb3c6MCAwIDEycHggM3B4IGJsYWNrO1xuICAgICAgICB9XG5cbiAgICBoMSxoMntcbiAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIH1cbiAgICBoMXtcbiAgICAgICAgZm9udC1zaXplOjMwcHg7XG4gICAgICAgIHBhZGRpbmc6MDtcbiAgICAgICAgbWFyZ2luOjA7XG4gICAgfVxuICAgIGgye1xuICAgICAgICBmb250LXNpemU6MTlweDtcbiAgICB9XG5cbiAgICBAa2V5ZnJhbWVzIHNwaW4ge1xuICAgICAgICBmcm9tIHtcbiAgICAgICAgICAgIHRyYW5zZm9ybTogcm90YXRlKDBkZWcpO1xuICAgICAgICB9XG4gICAgICAgIHRvIHtcbiAgICAgICAgICAgIHRyYW5zZm9ybTogcm90YXRlKDM2MGRlZyk7XG4gICAgICAgIH1cbiAgICB9XG4gICAgQGtleWZyYW1lcyBzcGluU2NhbGUge1xuICAgICAgICBmcm9tIHtcbiAgICAgICAgICAgIHRyYW5zZm9ybTogcm90YXRlKDBkZWcpIHNjYWxlKC43NCwuNzQpO1xuICAgICAgICB9XG4gICAgICAgIHRvIHtcbiAgICAgICAgICAgIHRyYW5zZm9ybTogcm90YXRlKDM2MGRlZykgc2NhbGUoLjc0LC43NCk7XG4gICAgICAgIH1cbiAgICB9XG4gICAgQGtleWZyYW1lcyBzcGluU2NhbGUyIHtcbiAgICAgICAgZnJvbSB7XG4gICAgICAgICAgICB0cmFuc2Zvcm06IHJvdGF0ZSgwZGVnKSBzY2FsZSguODQsLjg0KTtcbiAgICAgICAgfVxuICAgICAgICB0byB7XG4gICAgICAgICAgICB0cmFuc2Zvcm06IHJvdGF0ZSgzNjBkZWcpIHNjYWxlKC44NCwuODQpO1xuICAgICAgICB9XG4gICAgfVxuICAgIEBrZXlmcmFtZXMgc3Bpbi1yZSB7XG4gICAgICAgIGZyb20ge1xuICAgICAgICAgICAgdHJhbnNmb3JtOiByb3RhdGUoMGRlZyk7XG4gICAgICAgIH1cbiAgICAgICAgdG8ge1xuICAgICAgICAgICAgdHJhbnNmb3JtOiByb3RhdGUoLTM2MGRlZyk7XG4gICAgICAgIH1cbiAgICB9XG48L3N0eWxlPiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUF1RFksSUFBSSxBQUFDLENBQUMsQUFDVixXQUFXLElBQUksR0FBRyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQzdCLEtBQUssQ0FBRSxLQUFLLENBQ1osV0FBVyxNQUFNLENBQ2pCLFNBQVMsTUFBTSxBQUNuQixDQUFDLEFBQ0Qsa0JBQUcsQ0FBQyxBQUNBLE9BQU8sS0FBSyxBQUNoQixDQUFDLEFBQ0Qsb0JBQUssQ0FBQyxxQkFBTSxDQUFDLEFBQ1QsT0FBTyxDQUFFLEVBQUUsQ0FDWCxRQUFRLENBQUUsUUFBUSxDQUNsQixJQUFJLEtBQUssQ0FDVCxLQUFLLEtBQUssQ0FDVixRQUFRLENBQUMsQ0FDVCxPQUFPLENBQUMsQUFDWixDQUFDLEFBQ0QsMEJBQVcsQ0FBQyxBQUNSLFFBQVEsQ0FBRSxRQUFRLENBQ2xCLE1BQU0sTUFBTSxDQUNaLE9BQU8sTUFBTSxDQUNiLEtBQUssTUFBTSxDQUNYLElBQUksTUFBTSxDQUNWLGdCQUFnQixDQUFFLElBQUksY0FBYyxDQUFDLENBQ3JDLE9BQU8sQ0FBRSxFQUFFLEFBQ2YsQ0FBQyxBQUNELDBCQUFXLENBQUMsQUFDUixRQUFRLENBQUMsQ0FDVCxPQUFPLENBQUMsQ0FDUixRQUFRLENBQUUsUUFBUSxDQUNsQixTQUFTLENBQUUsTUFBTSxHQUFHLENBQUMsR0FBRyxDQUFDLENBQ3pCLE1BQU0sTUFBTSxDQUNaLE9BQU8sTUFBTSxDQUNiLEtBQUssTUFBTSxDQUNYLElBQUksT0FBTyxDQUNYLGNBQWMsQ0FBRSx3QkFBUyxDQUN6QixrQkFBa0IsQ0FBRSxPQUFPLENBQzNCLHlCQUF5QixDQUFFLFFBQVEsQ0FDbkMseUJBQXlCLENBQUUsTUFBTSxDQUNqQyxnQkFBZ0IsQ0FBRSxJQUFJLGtCQUFrQixDQUFDLENBQ3pDLE9BQU8sQ0FBRSxFQUFFLENBQ1gsT0FBTyxDQUFFLEVBQUUsQUFDZixDQUFDLEFBQ0QsNkJBQWMsQ0FBQyxBQUNYLFFBQVEsQ0FBQyxDQUNULE9BQU8sQ0FBQyxDQUNSLFFBQVEsQ0FBRSxRQUFRLENBQ2xCLFNBQVMsQ0FBRSxNQUFNLEVBQUUsQ0FBQyxFQUFFLENBQUMsQ0FDdkIsTUFBTSxNQUFNLENBQ1osT0FBTyxNQUFNLENBQ2IsS0FBSyxLQUFLLENBQ1YsSUFBSSxJQUFJLENBQ1IsY0FBYyxDQUFFLHlCQUFVLENBQzFCLGtCQUFrQixDQUFFLE9BQU8sQ0FDM0IseUJBQXlCLENBQUUsUUFBUSxDQUNuQyx5QkFBeUIsQ0FBRSxNQUFNLENBQ2pDLGdCQUFnQixDQUFFLElBQUksa0JBQWtCLENBQUMsQ0FDekMsT0FBTyxDQUFFLEdBQUcsQ0FDWixPQUFPLENBQUUsRUFBRSxBQUNmLENBQUMsQUFDRCw2QkFBYyxDQUFDLEFBQ1gsUUFBUSxDQUFFLFFBQVEsQ0FDbEIsTUFBTSxNQUFNLENBQ1osT0FBTyxNQUFNLENBQ2IsS0FBSyxLQUFLLENBQ1YsSUFBSSxLQUFLLENBQ1QsZ0JBQWdCLENBQUUsSUFBSSxjQUFjLENBQUMsQ0FDckMsT0FBTyxDQUFFLEVBQUUsQUFDZixDQUFDLEFBQ0Qsb0NBQXFCLENBQUMsQUFDbEIsUUFBUSxDQUFFLFFBQVEsQUFDdEIsQ0FBQyxBQU1ELG9CQUFLLENBQUMsQUFDRixVQUFVLENBQUUsR0FBRyxDQUFDLElBQUksQ0FBQyxXQUFXLENBQ2hDLGNBQWMsQ0FBRSxtQkFBSSxDQUNwQixrQkFBa0IsQ0FBRSxNQUFNLENBQzFCLHlCQUF5QixDQUFFLFFBQVEsQ0FDbkMseUJBQXlCLENBQUUsTUFBTSxBQUNyQyxDQUFDLEFBQ0QscUJBQU0sQ0FBQyxBQUNILFVBQVUsQ0FBRSxHQUFHLENBQUMsSUFBSSxDQUFDLFdBQVcsQ0FDaEMsY0FBYyxDQUFFLHNCQUFPLENBQ3ZCLGtCQUFrQixDQUFFLE1BQU0sQ0FDMUIseUJBQXlCLENBQUUsUUFBUSxDQUNuQyx5QkFBeUIsQ0FBRSxNQUFNLEFBQ3JDLENBQUMsQUFDRCxnQkFBQyxDQUFDLEFBQ0UsTUFBTSxJQUFJLEdBQUcsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUN4QixVQUFVLElBQUksQ0FDZCxXQUFXLEdBQUcsQ0FBQyxHQUFHLENBQUMsV0FBVyxBQUNsQyxDQUFDLEFBQ0QsNEJBQWEsQ0FBQyxBQUNWLE1BQU0sS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxLQUFLLENBQUMsQUFDOUIsQ0FBQyxBQUNELHdCQUFTLENBQUMsQUFDTixRQUFRLElBQUksQ0FDWixXQUFXLElBQUksQUFDbkIsQ0FBQyxBQUNELHdCQUFTLENBQUMsaUJBQUUsQ0FBQyxBQUNULFVBQVUsQ0FBRSxJQUFJLENBQ2hCLFFBQVEsQ0FBQyxDQUNULE1BQU0sSUFBSSxDQUNWLE9BQU8sQ0FBQyxDQUFDLElBQUksQUFDakIsQ0FBQyxBQUNELGlCQUFFLE1BQU0sQ0FBQyxFQUFFLENBQUMsZ0JBQUMsQ0FBQyxBQUNWLE1BQU0sSUFBSSxHQUFHLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FDeEIsTUFBTSxJQUFJLEFBQ2QsQ0FBQyxBQUNELHdCQUFTLENBQUMsRUFBRSxDQUFDLGlCQUFFLENBQUMsQUFDWixRQUFRLElBQUksQ0FBQyxDQUFDLENBQ2QsVUFBVSxJQUFJLENBQ2QsTUFBTSxJQUFJLENBQ1YsT0FBTyxDQUFDLENBQUMsSUFBSSxDQUNiLFdBQVcsTUFBTSxDQUNqQixXQUFXLEdBQUcsQ0FBQyxHQUFHLENBQUMsV0FBVyxBQUNsQyxDQUFDLEFBRUQsd0JBQVMsQ0FBQyxFQUFFLENBQUMsaUJBQUUsTUFBTSxDQUFDLEFBQ2xCLGNBQWMsSUFBSSxDQUFDLEdBQUcsQ0FBQyxJQUFJLENBQUMsR0FBRyxDQUMvQixXQUFXLEtBQUssR0FBRyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQUMsS0FBSyxDQUFDLENBQ3JDLE9BQU8sQ0FBQyxDQUFDLElBQUksQ0FDYixXQUFXLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxLQUFLLENBQ3hCLE1BQU0sSUFBSSxFQUFFLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxVQUFVLENBQ2hDLFVBQVUsSUFBSSxBQUNsQixDQUFDLEFBQ0Qsd0JBQVMsQ0FBQyxFQUFFLENBQUMsaUJBQUUsV0FBVyxJQUFJLENBQUMsTUFBTSxDQUFDLEFBQ2xDLGNBQWMsR0FBRyxDQUFDLElBQUksQ0FBQyxHQUFHLENBQUMsSUFBSSxDQUMvQixXQUFXLEtBQUssR0FBRyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQUMsS0FBSyxDQUFDLENBQ3JDLE9BQU8sQ0FBQyxDQUFDLElBQUksQ0FDYixXQUFXLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxLQUFLLENBQ3hCLE1BQU0sSUFBSSxFQUFFLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxVQUFVLENBQ2hDLFVBQVUsSUFBSSxBQUNsQixDQUFDLEFBQ0Qsd0JBQVMsQ0FBQyxFQUFFLENBQUMsaUJBQUUsV0FBVyxNQUFNLENBQUMsQUFDN0IsY0FBYyxHQUFHLENBQUMsR0FBRyxDQUFDLElBQUksQ0FBQyxJQUFJLENBQy9CLFdBQVcsS0FBSyxHQUFHLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FBQyxLQUFLLENBQUMsQ0FDckMsT0FBTyxDQUFDLENBQUMsSUFBSSxDQUNiLFdBQVcsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLEtBQUssQ0FDeEIsTUFBTSxJQUFJLEVBQUUsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUFDLFVBQVUsQ0FDaEMsVUFBVSxJQUFJLEFBQ2xCLENBQUMsQUFDRCx3QkFBUyxDQUFDLEVBQUUsQ0FBQyxpQkFBRSxZQUFZLE1BQU0sQ0FBQyxBQUM5QixjQUFjLElBQUksQ0FBQyxJQUFJLENBQUMsR0FBRyxDQUFDLEdBQUcsQ0FDL0IsV0FBVyxLQUFLLEdBQUcsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLEtBQUssQ0FBQyxDQUNyQyxPQUFPLENBQUMsQ0FBQyxJQUFJLENBQ2IsV0FBVyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsS0FBSyxDQUN4QixNQUFNLElBQUksRUFBRSxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsVUFBVSxDQUNoQyxVQUFVLElBQUksQUFDbEIsQ0FBQyxBQUVELHdCQUFTLENBQUMsRUFBRSxDQUFDLEVBQUUsTUFBTSxDQUFDLGdCQUFDLENBQUMsQUFDcEIsTUFBTSxJQUFJLEdBQUcsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUN4QixlQUFlLENBQUUsSUFBSSxBQUV6QixDQUFDLEFBQ0QsK0JBQWdCLENBQUMsQUFDYixjQUFjLElBQUksQ0FDbEIsVUFBVSxDQUFFLENBQUMsQ0FBQyxDQUFDLENBQUMsSUFBSSxDQUFDLEdBQUcsQ0FBQyxLQUFLLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLEtBQUssQ0FBQyxDQUM3QyxPQUFPLENBQUUsSUFBSSxDQUNiLGNBQWMsQ0FBRSxNQUFNLENBQ3RCLE1BQU0sR0FBRyxDQUNULE9BQU8sSUFBSSxDQUFDLElBQUksQ0FDaEIsV0FBVyxLQUFLLEdBQUcsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLEtBQUssQ0FBQyxDQUVyQyxlQUFlLElBQUksQ0FDbkIsT0FBTyxDQUFFLENBQUMsQUFFZCxDQUFDLEFBQ0QsT0FBTyxNQUFNLENBQUMsR0FBRyxDQUFDLFdBQVcsS0FBSyxDQUFDLENBQUMsQUFDaEMsK0JBQWdCLENBQUMsQUFDYixNQUFNLEdBQUcsQ0FDVCxXQUFXLElBQUksR0FBRyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQUMsR0FBRyxDQUFDLEFBQ2pDLENBQUMsQUFDTCxDQUFDLEFBRUQsMkJBQVksQ0FBQyxBQUNULFFBQVEsQ0FBRSxRQUFRLENBQ2xCLFVBQVUsSUFBSSxDQUNkLE9BQU8sQ0FBQyxDQUFDLElBQUksQ0FDYixVQUFVLFVBQVUsQ0FBQyxDQUFDLEtBQUssQ0FBQyxBQUNoQyxDQUFDLEFBQ0Qsa0JBQUcsQ0FBQyxBQUNBLFNBQVMsQ0FBRSxJQUFJLEFBQ2YsQ0FBQyxBQUNELDJCQUFZLENBQUMsQUFDVCxjQUFjLEdBQUcsQ0FDakIsV0FBVyxDQUFDLENBQUMsQ0FBQyxDQUFDLElBQUksQ0FBQyxHQUFHLENBQUMsS0FBSyxBQUNqQyxDQUFDLEFBRUwsaUJBQUUsQ0FBQyxpQkFBRSxDQUFDLEFBQ0YsVUFBVSxDQUFFLE1BQU0sQUFDdEIsQ0FBQyxBQUNELGlCQUFFLENBQUMsQUFDQyxVQUFVLElBQUksQ0FDZCxRQUFRLENBQUMsQ0FDVCxPQUFPLENBQUMsQUFDWixDQUFDLEFBQ0QsaUJBQUUsQ0FBQyxBQUNDLFVBQVUsSUFBSSxBQUNsQixDQUFDLEFBRUQsV0FBVyxtQkFBSyxDQUFDLEFBQ2IsSUFBSSxBQUFDLENBQUMsQUFDRixTQUFTLENBQUUsT0FBTyxJQUFJLENBQUMsQUFDM0IsQ0FBQyxBQUNELEVBQUUsQUFBQyxDQUFDLEFBQ0EsU0FBUyxDQUFFLE9BQU8sTUFBTSxDQUFDLEFBQzdCLENBQUMsQUFDTCxDQUFDLEFBQ0QsV0FBVyx3QkFBVSxDQUFDLEFBQ2xCLElBQUksQUFBQyxDQUFDLEFBQ0YsU0FBUyxDQUFFLE9BQU8sSUFBSSxDQUFDLENBQUMsTUFBTSxHQUFHLENBQUMsR0FBRyxDQUFDLEFBQzFDLENBQUMsQUFDRCxFQUFFLEFBQUMsQ0FBQyxBQUNBLFNBQVMsQ0FBRSxPQUFPLE1BQU0sQ0FBQyxDQUFDLE1BQU0sR0FBRyxDQUFDLEdBQUcsQ0FBQyxBQUM1QyxDQUFDLEFBQ0wsQ0FBQyxBQUNELFdBQVcseUJBQVcsQ0FBQyxBQUNuQixJQUFJLEFBQUMsQ0FBQyxBQUNGLFNBQVMsQ0FBRSxPQUFPLElBQUksQ0FBQyxDQUFDLE1BQU0sR0FBRyxDQUFDLEdBQUcsQ0FBQyxBQUMxQyxDQUFDLEFBQ0QsRUFBRSxBQUFDLENBQUMsQUFDQSxTQUFTLENBQUUsT0FBTyxNQUFNLENBQUMsQ0FBQyxNQUFNLEdBQUcsQ0FBQyxHQUFHLENBQUMsQUFDNUMsQ0FBQyxBQUNMLENBQUMsQUFDRCxXQUFXLHNCQUFRLENBQUMsQUFDaEIsSUFBSSxBQUFDLENBQUMsQUFDRixTQUFTLENBQUUsT0FBTyxJQUFJLENBQUMsQUFDM0IsQ0FBQyxBQUNELEVBQUUsQUFBQyxDQUFDLEFBQ0EsU0FBUyxDQUFFLE9BQU8sT0FBTyxDQUFDLEFBQzlCLENBQUMsQUFDTCxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var div4, div0, t0, div1, t1, div2, t2, div3, t3, div6, div5, img, t4, svg0, path0, path1, t5, svg1, path2, t6, h1, t7, t8, h20, t9, t10, h21, t11, t12, nav, ul, li0, a0, t13, t14, li1, a1, t15, t16, li2, a2, t17, t18, li3, a3, t19;

	return {
		c: function create() {
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			svg0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("svg");
			path0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("path");
			path1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("path");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			svg1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("svg");
			path2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("path");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Levy Anthony Adams");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			h20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Interactive Web Developer");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			h21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Please Choose below");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			nav = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("nav");
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ul");
			li0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Work History");
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Skills");
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Projects");
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Contact");
			this.h()
		},

		l: function claim(nodes) {
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n    ");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n\n    ");

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n    ");

			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);

			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div6);

			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "DIV", { class: true }, false);
			var div5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div5);

			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "IMG", { src: true, class: true, alt: true }, false);
			var img_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img);

			img_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div5_nodes, "\n\n        ");

			svg0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "svg", { class: true, width: true, height: true, version: true, viewBox: true, xmlns: true, "xmlns:cc": true, "xmlns:dc": true, "xmlns:osb": true, "xmlns:rdf": true }, true);
			var svg0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(svg0);

			path0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg0_nodes, "path", { d: true, fill: true, "stroke-width": true }, true);
			var path0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(path0);

			path0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			path1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg0_nodes, "path", { d: true, "stroke-width": true }, true);
			var path1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(path1);

			path1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			svg0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div5_nodes, "\n\n        ");

			svg1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "svg", { class: true, width: true, height: true, version: true, viewBox: true, xmlns: true, "xmlns:cc": true, "xmlns:dc": true, "xmlns:osb": true, "xmlns:rdf": true }, true);
			var svg1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(svg1);

			path2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg1_nodes, "path", { transform: true, d: true, fill: true, "stroke-width": true }, true);
			var path2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(path2);

			path2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			svg1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div6_nodes, "\n  \n");

			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "H1", { style: true, class: true }, false);
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "Levy Anthony Adams");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div6_nodes, "\n");

			h20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "H2", { class: true }, false);
			var h20_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h20);

			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h20_nodes, "Interactive Web Developer");
			h20_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div6_nodes, "\n\n");

			h21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "H2", { class: true, style: true }, false);
			var h21_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h21);

			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h21_nodes, "Please Choose below");
			h21_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div6_nodes, "\n\n");

			nav = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "NAV", { role: true, class: true }, false);
			var nav_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(nav);

			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nav_nodes, "UL", { class: true }, false);
			var ul_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			li0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", { class: true }, false);
			var li0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li0);

			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li0_nodes, "A", { href: true, class: true }, false);
			var a0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a0);

			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a0_nodes, "Work History");
			a0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			li0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ul_nodes, "\n        ");

			li1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", { class: true }, false);
			var li1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li1);

			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li1_nodes, "A", { href: true, class: true }, false);
			var a1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a1);

			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a1_nodes, "Skills");
			a1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			li1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ul_nodes, "\n        ");

			li2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", { class: true }, false);
			var li2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li2);

			a2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li2_nodes, "A", { href: true, class: true }, false);
			var a2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a2);

			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a2_nodes, "Projects");
			a2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			li2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ul_nodes, "\n        ");

			li3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", { class: true }, false);
			var li3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li3);

			a3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li3_nodes, "A", { href: true, class: true }, false);
			var a3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a3);

			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a3_nodes, "Contact");
			a3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			li3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			ul_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			nav_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div0, "class", "top-circle svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 9, 4, 248);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div1, "class", "top-dashed svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 10, 4, 283);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div2, "class", "bottom-circle svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 12, 4, 319);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div3, "class", "bottom-dashed svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 13, 4, 357);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div4, "class", "background-container svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 8, 0, 209);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img, "src", "profile.jpeg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img, "class", "profile-img svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img, "alt", "Levy Anthony Adams Profile Picture");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 17, 8, 466);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path0, "d", "m185.03 147.03c0.29362 28.491-17.677 55.422-42.969 67.929-30.732 16.052-71.107 11.16-96.601-12.53-20.34-18.105-29.779-47.749-22.423-74.131 7.5005-29.208 33.643-51.543 62.962-56.943 32.155-6.6565 68.021 6.741 86.315 34.375 8.1843 12.119 12.747 26.66 12.716 41.3z");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path0, "fill", "none");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path0, "stroke-width", "1.8428");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(path0, file, 24, 8, 911);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path1, "d", "m63.5 88.446c0.32868 8.4746-9.0805 15.209-16.996 12.164-8.1276-2.4222-11.467-13.5-6.0327-20.011 4.9141-6.9121 16.477-6.5003 20.887 0.74378 1.3908 2.0894 2.1456 4.5929 2.1413 7.1029z");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path1, "stroke-width", "3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(path1, file, 25, 8, 1228);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "class", "ring svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "width", "320px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "height", "320px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "version", "1.1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "viewBox", "0 0 210 297");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "xmlns", "http://www.w3.org/2000/svg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "xmlns:cc", "http://creativecommons.org/ns#");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "xmlns:dc", "http://purl.org/dc/elements/1.1/");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "xmlns:osb", "http://www.openswatchbook.org/uri/2009/osb");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "xmlns:rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(svg0, file, 19, 8, 561);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path2, "transform", "matrix(.35289 0 0 .33592 -83.215 -98.67)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path2, "d", "m526.81 501.29a232.99 230.14 0 0 0-118.69 32.295 36.417 38.256 0 0 1 7.6328 23.436 36.417 38.256 0 0 1-36.416 38.258 36.417 38.256 0 0 1-28.443-14.369 232.99 230.14 0 0 0-56.74 150.52 232.99 230.14 0 0 0 232.99 230.14 232.99 230.14 0 0 0 232.99-230.14 232.99 230.14 0 0 0-232.99-230.13 232.99 230.14 0 0 0-0.33594 0zm-175.92 79.619a232.99 230.14 0 0 1 57.227-47.324 36.417 38.256 0 0 0-28.783-14.82 36.417 38.256 0 0 0-36.418 38.256 36.417 38.256 0 0 0 7.9746 23.889z");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path2, "fill", "none");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path2, "stroke-width", "5.3523");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(path2, file, 33, 8, 1815);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "class", "ring1 svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "width", "320px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "height", "320px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "version", "1.1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "viewBox", "0 0 210 297");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "xmlns", "http://www.w3.org/2000/svg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "xmlns:cc", "http://creativecommons.org/ns#");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "xmlns:dc", "http://purl.org/dc/elements/1.1/");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "xmlns:osb", "http://www.openswatchbook.org/uri/2009/osb");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "xmlns:rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(svg1, file, 28, 8, 1464);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div5, "class", "img-wrapper svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div5, file, 16, 4, 432);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(h1, "padding", "10px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(h1, "class", "svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 38, 0, 2410);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(h20, "class", "svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h20, file, 39, 0, 2459);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(h21, "class", "list-eyebrow svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(h21, "margin-top", "40px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(h21, "font-size", "14px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h21, file, 41, 0, 2495);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a0, "href", "");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a0, "class", "svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a0, file, 45, 12, 2648);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(li0, "class", "svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li0, file, 45, 8, 2644);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a1, "href", "");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a1, "class", "svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a1, file, 46, 12, 2693);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(li1, "class", "svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li1, file, 46, 8, 2689);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a2, "href", "");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a2, "class", "svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a2, file, 47, 12, 2732);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(li2, "class", "svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li2, file, 47, 8, 2728);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a3, "href", "");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a3, "class", "svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a3, file, 48, 12, 2773);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(li3, "class", "svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li3, file, 48, 8, 2769);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(ul, "class", "svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ul, file, 44, 4, 2631);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(nav, "role", "navigation");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(nav, "class", "nav-list svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(nav, file, 43, 0, 2586);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div6, "class", "intro-container svelte-11i1ky9");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div6, file, 15, 0, 398);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div4, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t3, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div6, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, div5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div5, img);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div5, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div5, svg0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg0, path0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg0, path1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div5, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div5, svg1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg1, path2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h1, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, h20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h20, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, h21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h21, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, nav);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(nav, ul);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, li0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li0, a0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a0, t13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, li1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li1, a1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a1, t15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, t16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, li2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li2, a2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a2, t17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, t18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, li3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li3, a3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a3, t19);
		},

		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div4);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t3);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div6);
			}
		}
	};
}

class Work_history extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-11i1ky9-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, null, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Work_history);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvbm9kZV9tb2R1bGVzL2Nyb3NzZmFkZS5qcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7O0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFxRDtBQUNQO0FBQzlDLHdCQUF3QixtRUFBUztBQUNqQyxVQUFVLHdEQUFVO0FBQ3BCO0FBQ0E7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQSxjQUFjLHNEQUFRO0FBQ3RCO0FBQ0EsNkJBQTZCO0FBQzdCLDJCQUEyQjtBQUMzQjtBQUNBO0FBQ0E7QUFDQSxDQUFDOztBQUV3QiIsImZpbGUiOiI2MjQ0MzYzYjdiOTM1MmU0ZWQ1YS9zaXRlc19wcm9mZXNzaW9uYWwkNDVwcm9maWxlJDQ1d2ViX3dvcmskNDVoaXN0b3J5LnNpdGVzX3Byb2Zlc3Npb25hbCQ0NXByb2ZpbGUkNDV3ZWJfd29yayQ0NWhpc3RvcnkuanMiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgeyBxdWludEluT3V0LCBxdWludE91dCB9IGZyb20gXCJzdmVsdGUvZWFzaW5nXCI7XG5pbXBvcnQgeyBjcm9zc2ZhZGUgfSBmcm9tIFwic3ZlbHRlL3RyYW5zaXRpb25cIjtcbmNvbnN0IFtzZW5kLCByZWNlaXZlXSA9IGNyb3NzZmFkZSh7XG4gIGVhc2luZzogcXVpbnRJbk91dCxcbiAgZHVyYXRpb246IGQgPT4gTWF0aC5zcXJ0KGQqMTIwMCksXG4gIGZhbGxiYWNrKG5vZGUsIHBhcmFtcykge1xuICAgIGNvbnN0IHN0eWxlID0gZ2V0Q29tcHV0ZWRTdHlsZShub2RlKTtcbiAgICBjb25zdCB0cmFuc2Zvcm0gPSBzdHlsZS50cmFuc2Zvcm0gPT09IFwibm9uZVwiID8gXCJcIiA6IHN0eWxlLnRyYW5zZm9ybTtcblxuICAgIHJldHVybiB7XG4gICAgICBkdXJhdGlvbjogMTIwMCxcbiAgICAgIGVhc2luZzogcXVpbnRPdXQsXG4gICAgICBjc3M6IHQgPT4gYFxuICAgICAgICAgICAgICAgIHRyYW5zZm9ybTogJHt0cmFuc2Zvcm19O1xuICAgICAgICAgICAgICAgIG9wYWNpdHk6ICR7dH1cbiAgICAgICAgICAgIGBcbiAgICB9O1xuICB9XG59KTtcblxuZXhwb3J0IHsgc2VuZCwgcmVjZWl2ZSB9O1xuIl0sInNvdXJjZVJvb3QiOiIifQ==