(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/routes/index.svelte generated by Svelte v3.8.0 */


const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-t62ywt-style';
	style.textContent = "h1.svelte-t62ywt{font-size:39px;text-align:center;margin:40px 0}h2.svelte-t62ywt{padding:8px;box-shadow:0px 0px 0px 0px rgb(121, 119, 119);transition:all 0.5s ease-in-out;transform:scale(1);text-align:center}p.svelte-t62ywt{text-align:center;font-size:20px}svg.svelte-t62ywt{transition:all 0.3s ease-in-out;transform:scale(1) translate(0, 0)}.logo-container.svelte-t62ywt{display:flex;justify-content:center;align-items:center}.logo-container.svelte-t62ywt:hover>h2.svelte-t62ywt{box-shadow:1px 12px 12px 1px rgb(121, 119, 119);transition:all 0.5s ease-in-out;transform:scale(1.24);color:white;z-index:5}.logo-container.svelte-t62ywt:hover>.container.svelte-t62ywt{transform:translate(-40px, 0);transition:transform 0.5s ease-in-out}.logo-container.svelte-t62ywt>.container.svelte-t62ywt{position:relative;width:80px;height:80px;transition:transform 0.5s ease-in-out}.logo-container.svelte-t62ywt>.container>svg.svelte-t62ywt{position:absolute;top:0;left:0}.logo-container.svelte-t62ywt>.container>.ring1.svelte-t62ywt{transition:all 0.3s ease-in-out;animation-name:svelte-t62ywt-spin;animation-duration:5000ms;animation-iteration-count:infinite;animation-timing-function:linear;transform-origin:50% 50%}.logo-container.svelte-t62ywt>.container>.ring.svelte-t62ywt,.logo-container.svelte-t62ywt>.container>.ring2.svelte-t62ywt{transition:all 0.3s ease-in-out;animation-name:svelte-t62ywt-spin-re;animation-duration:5000ms;animation-iteration-count:infinite;animation-timing-function:linear}@keyframes svelte-t62ywt-spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}@keyframes svelte-t62ywt-spin-re{from{transform:rotate(0deg)}to{transform:rotate(-360deg)}}a.svelte-t62ywt{text-decoration:none;display:inline-block;margin-left:auto;width:100%}body{background:rgb(187, 187, 217)}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gICAgaDEge1xuICAgICAgICBmb250LXNpemU6IDM5cHg7XG4gICAgICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICAgICAgbWFyZ2luOiA0MHB4IDA7XG4gICAgfVxuICAgIGgyIHtcbiAgICAgICAgcGFkZGluZzogOHB4O1xuICAgICAgICBib3gtc2hhZG93OiAwcHggMHB4IDBweCAwcHggcmdiKDEyMSwgMTE5LCAxMTkpO1xuICAgICAgICB0cmFuc2l0aW9uOiBhbGwgMC41cyBlYXNlLWluLW91dDtcbiAgICAgICAgdHJhbnNmb3JtOiBzY2FsZSgxKTtcbiAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIH1cbiAgICBwIHtcbiAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgICAgICBmb250LXNpemU6IDIwcHg7XG4gICAgfVxuICAgIHN2ZyB7XG4gICAgICAgIHRyYW5zaXRpb246IGFsbCAwLjNzIGVhc2UtaW4tb3V0O1xuICAgICAgICB0cmFuc2Zvcm06IHNjYWxlKDEpIHRyYW5zbGF0ZSgwLCAwKTtcbiAgICB9XG4gICAgLmxvZ28tY29udGFpbmVyIHtcbiAgICAgICAgZGlzcGxheTogZmxleDtcbiAgICAgICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG4gICAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gICAgfVxuICAgIC5sb2dvLWNvbnRhaW5lcjpob3ZlciA+IGgyIHtcbiAgICAgICAgYm94LXNoYWRvdzogMXB4IDEycHggMTJweCAxcHggcmdiKDEyMSwgMTE5LCAxMTkpO1xuICAgICAgICB0cmFuc2l0aW9uOiBhbGwgMC41cyBlYXNlLWluLW91dDtcbiAgICAgICAgdHJhbnNmb3JtOiBzY2FsZSgxLjI0KTtcbiAgICAgICAgY29sb3I6IHdoaXRlO1xuICAgICAgICB6LWluZGV4OiA1O1xuICAgIH1cbiAgICAubG9nby1jb250YWluZXI6aG92ZXIgPiAuY29udGFpbmVyIHtcbiAgICAgICAgdHJhbnNmb3JtOiB0cmFuc2xhdGUoLTQwcHgsIDApO1xuICAgICAgICB0cmFuc2l0aW9uOiB0cmFuc2Zvcm0gMC41cyBlYXNlLWluLW91dDtcbiAgICB9XG4gICAgLmxvZ28tY29udGFpbmVyID4gLmNvbnRhaW5lciB7XG4gICAgICAgIHBvc2l0aW9uOiByZWxhdGl2ZTtcbiAgICAgICAgd2lkdGg6IDgwcHg7XG4gICAgICAgIGhlaWdodDogODBweDtcbiAgICAgICAgdHJhbnNpdGlvbjogdHJhbnNmb3JtIDAuNXMgZWFzZS1pbi1vdXQ7XG4gICAgfVxuICAgIC5sb2dvLWNvbnRhaW5lciA+IC5jb250YWluZXIgPiBzdmcge1xuICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gICAgICAgIHRvcDogMDtcbiAgICAgICAgbGVmdDogMDtcbiAgICB9XG4gICAgLmxvZ28tY29udGFpbmVyID4gLmNvbnRhaW5lciA+IC5yaW5nMSB7XG4gICAgICAgIHRyYW5zaXRpb246IGFsbCAwLjNzIGVhc2UtaW4tb3V0O1xuICAgICAgICBhbmltYXRpb24tbmFtZTogc3BpbjtcbiAgICAgICAgYW5pbWF0aW9uLWR1cmF0aW9uOiA1MDAwbXM7XG4gICAgICAgIGFuaW1hdGlvbi1pdGVyYXRpb24tY291bnQ6IGluZmluaXRlO1xuICAgICAgICBhbmltYXRpb24tdGltaW5nLWZ1bmN0aW9uOiBsaW5lYXI7XG4gICAgICAgIHRyYW5zZm9ybS1vcmlnaW46IDUwJSA1MCU7XG4gICAgfVxuICAgIC5sb2dvLWNvbnRhaW5lciA+IC5jb250YWluZXIgPiAucmluZyxcbiAgICAubG9nby1jb250YWluZXIgPiAuY29udGFpbmVyID4gLnJpbmcyIHtcbiAgICAgICAgdHJhbnNpdGlvbjogYWxsIDAuM3MgZWFzZS1pbi1vdXQ7XG4gICAgICAgIGFuaW1hdGlvbi1uYW1lOiBzcGluLXJlO1xuICAgICAgICBhbmltYXRpb24tZHVyYXRpb246IDUwMDBtcztcbiAgICAgICAgYW5pbWF0aW9uLWl0ZXJhdGlvbi1jb3VudDogaW5maW5pdGU7XG4gICAgICAgIGFuaW1hdGlvbi10aW1pbmctZnVuY3Rpb246IGxpbmVhcjtcbiAgICB9XG4gICAgQGtleWZyYW1lcyBzcGluIHtcbiAgICAgICAgZnJvbSB7XG4gICAgICAgICAgICB0cmFuc2Zvcm06IHJvdGF0ZSgwZGVnKTtcbiAgICAgICAgfVxuICAgICAgICB0byB7XG4gICAgICAgICAgICB0cmFuc2Zvcm06IHJvdGF0ZSgzNjBkZWcpO1xuICAgICAgICB9XG4gICAgfVxuICAgIEBrZXlmcmFtZXMgc3Bpbi1yZSB7XG4gICAgICAgIGZyb20ge1xuICAgICAgICAgICAgdHJhbnNmb3JtOiByb3RhdGUoMGRlZyk7XG4gICAgICAgIH1cbiAgICAgICAgdG8ge1xuICAgICAgICAgICAgdHJhbnNmb3JtOiByb3RhdGUoLTM2MGRlZyk7XG4gICAgICAgIH1cbiAgICB9XG4gICAgYSB7XG4gICAgICAgIHRleHQtZGVjb3JhdGlvbjogbm9uZTtcbiAgICAgICAgZGlzcGxheTogaW5saW5lLWJsb2NrO1xuICAgICAgICBtYXJnaW4tbGVmdDogYXV0bztcbiAgICAgICAgd2lkdGg6IDEwMCU7XG4gICAgfVxuICAgIDpnbG9iYWwoYm9keSkge1xuICAgICAgICBiYWNrZ3JvdW5kOiByZ2IoMTg3LCAxODcsIDIxNyk7XG4gICAgfVxuPC9zdHlsZT5cblxuPGgxPldlbGNvbWUhPC9oMT5cbjxoMj5Zb3UndmUgcHJvYmFibHkgcmVhY2hlZCB0aGlzIGJ5IGFjY2lkZW50LjwvaDI+XG48cD5BcmUgeW91IGJ5IGNoYW5jZSBsb29raW5nIGZvci4uPC9wPlxuPGEgaHJlZj1cIi4vZGV2XCI+XG4gICAgPGRpdiBjbGFzcz1cImxvZ28tY29udGFpbmVyXCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgICAgICAgICAgIDxzdmdcbiAgICAgICAgICAgICAgICBjbGFzcz1cInJpbmdcIlxuICAgICAgICAgICAgICAgIHdpZHRoPVwiODBweFwiXG4gICAgICAgICAgICAgICAgaGVpZ2h0PVwiODBweFwiXG4gICAgICAgICAgICAgICAgdmVyc2lvbj1cIjEuMVwiXG4gICAgICAgICAgICAgICAgdmlld0JveD1cIjAgMCAyMTAgMjk3XCJcbiAgICAgICAgICAgICAgICB4bWxucz1cImh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnXCJcbiAgICAgICAgICAgICAgICB4bWxuczpjYz1cImh0dHA6Ly9jcmVhdGl2ZWNvbW1vbnMub3JnL25zI1wiXG4gICAgICAgICAgICAgICAgeG1sbnM6ZGM9XCJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xL1wiXG4gICAgICAgICAgICAgICAgeG1sbnM6b3NiPVwiaHR0cDovL3d3dy5vcGVuc3dhdGNoYm9vay5vcmcvdXJpLzIwMDkvb3NiXCJcbiAgICAgICAgICAgICAgICB4bWxuczpyZGY9XCJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjXCI+XG4gICAgICAgICAgICAgICAgPGdcbiAgICAgICAgICAgICAgICAgICAgdHJhbnNmb3JtPVwibWF0cml4KC0uNjA0MjQgMCAwIC0uNjM3OSAxNjQuNTUgMjQwLjgzKVwiXG4gICAgICAgICAgICAgICAgICAgIHN0cm9rZT1cIiMwMDBcIj5cbiAgICAgICAgICAgICAgICAgICAgPHBhdGhcbiAgICAgICAgICAgICAgICAgICAgICAgIGQ9XCJtMTg1LjAzIDE0Ny4wM2MwLjI5MzYyIDI4LjQ5MS0xNy42NzcgNTUuNDIyLTQyLjk2OSA2Ny45MjktMzAuNzMyIDE2LjA1Mi03MS4xMDcgMTEuMTYtOTYuNjAxLTEyLjUzLTIwLjM0LTE4LjEwNS0yOS43NzktNDcuNzQ5LTIyLjQyMy03NC4xMzEgNy41MDA1LTI5LjIwOCAzMy42NDMtNTEuNTQzIDYyLjk2Mi01Ni45NDMgMzIuMTU1LTYuNjU2NSA2OC4wMjEgNi43NDEgODYuMzE1IDM0LjM3NSA4LjE4NDMgMTIuMTE5IDEyLjc0NyAyNi42NiAxMi43MTYgNDEuM3pcIlxuICAgICAgICAgICAgICAgICAgICAgICAgZmlsbD1cIm5vbmVcIlxuICAgICAgICAgICAgICAgICAgICAgICAgc3Ryb2tlLXdpZHRoPVwiMS44NDI4XCIgLz5cbiAgICAgICAgICAgICAgICAgICAgPHBhdGhcbiAgICAgICAgICAgICAgICAgICAgICAgIGQ9XCJtNjMuNSA4OC40NDZjMC4zMjg2OCA4LjQ3NDYtOS4wODA1IDE1LjIwOS0xNi45OTYgMTIuMTY0LTguMTI3Ni0yLjQyMjItMTEuNDY3LTEzLjUtNi4wMzI3LTIwLjAxMSA0LjkxNDEtNi45MTIxIDE2LjQ3Ny02LjUwMDMgMjAuODg3IDAuNzQzNzggMS4zOTA4IDIuMDg5NCAyLjE0NTYgNC41OTI5IDIuMTQxMyA3LjEwMjl6XCJcbiAgICAgICAgICAgICAgICAgICAgICAgIHN0cm9rZS13aWR0aD1cIjNcIiAvPlxuICAgICAgICAgICAgICAgIDwvZz5cbiAgICAgICAgICAgIDwvc3ZnPlxuXG4gICAgICAgICAgICA8c3ZnXG4gICAgICAgICAgICAgICAgY2xhc3M9XCJyaW5nMVwiXG4gICAgICAgICAgICAgICAgd2lkdGg9XCI4MHB4XCJcbiAgICAgICAgICAgICAgICBoZWlnaHQ9XCI4MHB4XCJcbiAgICAgICAgICAgICAgICB2ZXJzaW9uPVwiMS4xXCJcbiAgICAgICAgICAgICAgICB2aWV3Qm94PVwiMCAwIDIxMCAyOTdcIlxuICAgICAgICAgICAgICAgIHhtbG5zPVwiaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmdcIlxuICAgICAgICAgICAgICAgIHhtbG5zOmNjPVwiaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbnMjXCJcbiAgICAgICAgICAgICAgICB4bWxuczpkYz1cImh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvXCJcbiAgICAgICAgICAgICAgICB4bWxuczpvc2I9XCJodHRwOi8vd3d3Lm9wZW5zd2F0Y2hib29rLm9yZy91cmkvMjAwOS9vc2JcIlxuICAgICAgICAgICAgICAgIHhtbG5zOnJkZj1cImh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyNcIj5cbiAgICAgICAgICAgICAgICA8ZyB0cmFuc2Zvcm09XCJtYXRyaXgoLjc0OTc2IDAgMCAuNzg3NjMgNjIuMzkxIDc3LjcxNilcIj5cbiAgICAgICAgICAgICAgICAgICAgPHBhdGhcbiAgICAgICAgICAgICAgICAgICAgICAgIHRyYW5zZm9ybT1cIm1hdHJpeCguMzUyODkgMCAwIC4zMzU5MiAtODMuMjE1IC05OC42NylcIlxuICAgICAgICAgICAgICAgICAgICAgICAgZD1cIm01MjYuODEgNTAxLjI5YTIzMi45OSAyMzAuMTQgMCAwIDAtMTE4LjY5IDMyLjI5NSAzNi40MTcgMzguMjU2IDAgMCAxIDcuNjMyOCAyMy40MzYgMzYuNDE3IDM4LjI1NiAwIDAgMS0zNi40MTYgMzguMjU4IDM2LjQxNyAzOC4yNTYgMCAwIDEtMjguNDQzLTE0LjM2OSAyMzIuOTkgMjMwLjE0IDAgMCAwLTU2Ljc0IDE1MC41MiAyMzIuOTkgMjMwLjE0IDAgMCAwIDIzMi45OSAyMzAuMTQgMjMyLjk5IDIzMC4xNCAwIDAgMCAyMzIuOTktMjMwLjE0IDIzMi45OSAyMzAuMTQgMCAwIDAtMjMyLjk5LTIzMC4xMyAyMzIuOTkgMjMwLjE0IDAgMCAwLTAuMzM1OTQgMHptLTE3NS45MiA3OS42MTlhMjMyLjk5IDIzMC4xNCAwIDAgMSA1Ny4yMjctNDcuMzI0IDM2LjQxNyAzOC4yNTYgMCAwIDAtMjguNzgzLTE0LjgyIDM2LjQxNyAzOC4yNTYgMCAwIDAtMzYuNDE4IDM4LjI1NiAzNi40MTcgMzguMjU2IDAgMCAwIDcuOTc0NiAyMy44ODl6XCJcbiAgICAgICAgICAgICAgICAgICAgICAgIGZpbGw9XCJub25lXCJcbiAgICAgICAgICAgICAgICAgICAgICAgIHN0cm9rZT1cIiMwMDBcIlxuICAgICAgICAgICAgICAgICAgICAgICAgc3Ryb2tlLXdpZHRoPVwiNS4zNTIzXCIgLz5cbiAgICAgICAgICAgICAgICA8L2c+XG4gICAgICAgICAgICA8L3N2Zz5cblxuICAgICAgICAgICAgPHN2Z1xuICAgICAgICAgICAgICAgIGNsYXNzPVwicmluZzJcIlxuICAgICAgICAgICAgICAgIHdpZHRoPVwiODBweFwiXG4gICAgICAgICAgICAgICAgaGVpZ2h0PVwiODBweFwiXG4gICAgICAgICAgICAgICAgdmVyc2lvbj1cIjEuMVwiXG4gICAgICAgICAgICAgICAgdmlld0JveD1cIjAgMCAyMTAgMjk3XCJcbiAgICAgICAgICAgICAgICB4bWxucz1cImh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnXCJcbiAgICAgICAgICAgICAgICB4bWxuczpjYz1cImh0dHA6Ly9jcmVhdGl2ZWNvbW1vbnMub3JnL25zI1wiXG4gICAgICAgICAgICAgICAgeG1sbnM6ZGM9XCJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xL1wiXG4gICAgICAgICAgICAgICAgeG1sbnM6b3NiPVwiaHR0cDovL3d3dy5vcGVuc3dhdGNoYm9vay5vcmcvdXJpLzIwMDkvb3NiXCJcbiAgICAgICAgICAgICAgICB4bWxuczpyZGY9XCJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjXCI+XG4gICAgICAgICAgICAgICAgPHBhdGhcbiAgICAgICAgICAgICAgICAgICAgY2xhc3M9XCJsb2dvLWdyb3VwMVwiXG4gICAgICAgICAgICAgICAgICAgIHRyYW5zZm9ybT1cInNjYWxlKC4yNjQ1OClcIlxuICAgICAgICAgICAgICAgICAgICBkPVwibTM4Ny45NCAyNjMuNTNhMzEwLjc2IDI5Mi4xOSAwIDAgMC0xNTguMTIgNDEuMDA0IDQ4LjU3MSA0OC41NzEgMCAwIDEgMTAuMTggMjkuNzU0IDQ4LjU3MSA0OC41NzEgMCAwIDEtNDguNTcyIDQ4LjU3MiA0OC41NzEgNDguNTcxIDAgMCAxLTM3LjkzNi0xOC4yNCAzMTAuNzYgMjkyLjE5IDAgMCAwLTc1LjY4IDE5MS4xIDMxMC43NiAyOTIuMTkgMCAwIDAgMzEwLjc2IDI5Mi4xOSAzMTAuNzYgMjkyLjE5IDAgMCAwIDMxMC43Ni0yOTIuMTkgMzEwLjc2IDI5Mi4xOSAwIDAgMC0zMTAuNzYtMjkyLjE5IDMxMC43NiAyOTIuMTkgMCAwIDAtMC42Mjg5MSAwelwiXG4gICAgICAgICAgICAgICAgICAgIGZpbGw9XCJub25lXCJcbiAgICAgICAgICAgICAgICAgICAgc3Ryb2tlPVwiIzAwMFwiXG4gICAgICAgICAgICAgICAgICAgIHN0cm9rZS13aWR0aD1cIjYuOTY1XCIgLz5cbiAgICAgICAgICAgIDwvc3ZnPlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGgyPk5lYnVsYSBXZWIgRGV2ZWxvcG1lbnQ8L2gyPlxuICAgIDwvZGl2PlxuPC9hPlxuPGgyIHN0eWxlPVwidGV4dC1hbGlnbjpjZW50ZXI7Zm9udC1zaXplOjQwcHg7bWFyZ2luOjQwcHggMDtcIj5PUi4uPC9oMj5cbjxhIGhyZWY9XCIuL25lYnVsYVwiPlxuICAgIDxkaXYgY2xhc3M9XCJsb2dvLWNvbnRhaW5lclwiPlxuICAgICAgICA8aDI+Sm95c3RpY2sgTmVidWxhIEdhbWluZzwvaDI+XG4gICAgPC9kaXY+XG48L2E+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBSUksRUFBRSxjQUFDLENBQUMsQUFDQSxTQUFTLENBQUUsSUFBSSxDQUNmLFVBQVUsQ0FBRSxNQUFNLENBQ2xCLE1BQU0sQ0FBRSxJQUFJLENBQUMsQ0FBQyxBQUNsQixDQUFDLEFBQ0QsRUFBRSxjQUFDLENBQUMsQUFDQSxPQUFPLENBQUUsR0FBRyxDQUNaLFVBQVUsQ0FBRSxHQUFHLENBQUMsR0FBRyxDQUFDLEdBQUcsQ0FBQyxHQUFHLENBQUMsSUFBSSxHQUFHLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FDOUMsVUFBVSxDQUFFLEdBQUcsQ0FBQyxJQUFJLENBQUMsV0FBVyxDQUNoQyxTQUFTLENBQUUsTUFBTSxDQUFDLENBQUMsQ0FDbkIsVUFBVSxDQUFFLE1BQU0sQUFDdEIsQ0FBQyxBQUNELENBQUMsY0FBQyxDQUFDLEFBQ0MsVUFBVSxDQUFFLE1BQU0sQ0FDbEIsU0FBUyxDQUFFLElBQUksQUFDbkIsQ0FBQyxBQUNELEdBQUcsY0FBQyxDQUFDLEFBQ0QsVUFBVSxDQUFFLEdBQUcsQ0FBQyxJQUFJLENBQUMsV0FBVyxDQUNoQyxTQUFTLENBQUUsTUFBTSxDQUFDLENBQUMsQ0FBQyxVQUFVLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxBQUN2QyxDQUFDLEFBQ0QsZUFBZSxjQUFDLENBQUMsQUFDYixPQUFPLENBQUUsSUFBSSxDQUNiLGVBQWUsQ0FBRSxNQUFNLENBQ3ZCLFdBQVcsQ0FBRSxNQUFNLEFBQ3ZCLENBQUMsQUFDRCw2QkFBZSxNQUFNLENBQUcsRUFBRSxjQUFDLENBQUMsQUFDeEIsVUFBVSxDQUFFLEdBQUcsQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLEdBQUcsQ0FBQyxJQUFJLEdBQUcsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUNoRCxVQUFVLENBQUUsR0FBRyxDQUFDLElBQUksQ0FBQyxXQUFXLENBQ2hDLFNBQVMsQ0FBRSxNQUFNLElBQUksQ0FBQyxDQUN0QixLQUFLLENBQUUsS0FBSyxDQUNaLE9BQU8sQ0FBRSxDQUFDLEFBQ2QsQ0FBQyxBQUNELDZCQUFlLE1BQU0sQ0FBRyxVQUFVLGNBQUMsQ0FBQyxBQUNoQyxTQUFTLENBQUUsVUFBVSxLQUFLLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FDOUIsVUFBVSxDQUFFLFNBQVMsQ0FBQyxJQUFJLENBQUMsV0FBVyxBQUMxQyxDQUFDLEFBQ0QsNkJBQWUsQ0FBRyxVQUFVLGNBQUMsQ0FBQyxBQUMxQixRQUFRLENBQUUsUUFBUSxDQUNsQixLQUFLLENBQUUsSUFBSSxDQUNYLE1BQU0sQ0FBRSxJQUFJLENBQ1osVUFBVSxDQUFFLFNBQVMsQ0FBQyxJQUFJLENBQUMsV0FBVyxBQUMxQyxDQUFDLEFBQ0QsNkJBQWUsQ0FBRyxVQUFVLENBQUcsR0FBRyxjQUFDLENBQUMsQUFDaEMsUUFBUSxDQUFFLFFBQVEsQ0FDbEIsR0FBRyxDQUFFLENBQUMsQ0FDTixJQUFJLENBQUUsQ0FBQyxBQUNYLENBQUMsQUFDRCw2QkFBZSxDQUFHLFVBQVUsQ0FBRyxNQUFNLGNBQUMsQ0FBQyxBQUNuQyxVQUFVLENBQUUsR0FBRyxDQUFDLElBQUksQ0FBQyxXQUFXLENBQ2hDLGNBQWMsQ0FBRSxrQkFBSSxDQUNwQixrQkFBa0IsQ0FBRSxNQUFNLENBQzFCLHlCQUF5QixDQUFFLFFBQVEsQ0FDbkMseUJBQXlCLENBQUUsTUFBTSxDQUNqQyxnQkFBZ0IsQ0FBRSxHQUFHLENBQUMsR0FBRyxBQUM3QixDQUFDLEFBQ0QsNkJBQWUsQ0FBRyxVQUFVLENBQUcsbUJBQUssQ0FDcEMsNkJBQWUsQ0FBRyxVQUFVLENBQUcsTUFBTSxjQUFDLENBQUMsQUFDbkMsVUFBVSxDQUFFLEdBQUcsQ0FBQyxJQUFJLENBQUMsV0FBVyxDQUNoQyxjQUFjLENBQUUscUJBQU8sQ0FDdkIsa0JBQWtCLENBQUUsTUFBTSxDQUMxQix5QkFBeUIsQ0FBRSxRQUFRLENBQ25DLHlCQUF5QixDQUFFLE1BQU0sQUFDckMsQ0FBQyxBQUNELFdBQVcsa0JBQUssQ0FBQyxBQUNiLElBQUksQUFBQyxDQUFDLEFBQ0YsU0FBUyxDQUFFLE9BQU8sSUFBSSxDQUFDLEFBQzNCLENBQUMsQUFDRCxFQUFFLEFBQUMsQ0FBQyxBQUNBLFNBQVMsQ0FBRSxPQUFPLE1BQU0sQ0FBQyxBQUM3QixDQUFDLEFBQ0wsQ0FBQyxBQUNELFdBQVcscUJBQVEsQ0FBQyxBQUNoQixJQUFJLEFBQUMsQ0FBQyxBQUNGLFNBQVMsQ0FBRSxPQUFPLElBQUksQ0FBQyxBQUMzQixDQUFDLEFBQ0QsRUFBRSxBQUFDLENBQUMsQUFDQSxTQUFTLENBQUUsT0FBTyxPQUFPLENBQUMsQUFDOUIsQ0FBQyxBQUNMLENBQUMsQUFDRCxDQUFDLGNBQUMsQ0FBQyxBQUNDLGVBQWUsQ0FBRSxJQUFJLENBQ3JCLE9BQU8sQ0FBRSxZQUFZLENBQ3JCLFdBQVcsQ0FBRSxJQUFJLENBQ2pCLEtBQUssQ0FBRSxJQUFJLEFBQ2YsQ0FBQyxBQUNPLElBQUksQUFBRSxDQUFDLEFBQ1gsVUFBVSxDQUFFLElBQUksR0FBRyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQUMsR0FBRyxDQUFDLEFBQ2xDLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var h1, t0, t1, h20, t2, t3, p, t4, t5, a0, div1, div0, svg0, g0, path0, path1, t6, svg1, g1, path2, t7, svg2, path3, t8, h21, t9, t10, h22, t11, t12, a1, div2, h23, t13;

	return {
		c: function create() {
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Welcome!");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			h20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("You've probably reached this by accident.");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Are you by chance looking for..");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			svg0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("svg");
			g0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			path0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("path");
			path1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("path");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			svg1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("svg");
			g1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			path2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("path");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			svg2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("svg");
			path3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("path");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			h21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Nebula Web Development");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			h22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("OR..");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Joystick Nebula Gaming");
			this.h()
		},

		l: function claim(nodes) {
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "H1", { class: true }, false);
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "Welcome!");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			h20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "H2", { class: true }, false);
			var h20_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h20);

			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h20_nodes, "You've probably reached this by accident.");
			h20_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true }, false);
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);

			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p_nodes, "Are you by chance looking for..");
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "A", { href: true, class: true }, false);
			var a0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a0);

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a0_nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			svg0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "svg", { class: true, width: true, height: true, version: true, viewBox: true, xmlns: true, "xmlns:cc": true, "xmlns:dc": true, "xmlns:osb": true, "xmlns:rdf": true }, true);
			var svg0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(svg0);

			g0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg0_nodes, "g", { transform: true, stroke: true }, true);
			var g0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g0);

			path0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(g0_nodes, "path", { d: true, fill: true, "stroke-width": true }, true);
			var path0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(path0);

			path0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			path1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(g0_nodes, "path", { d: true, "stroke-width": true }, true);
			var path1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(path1);

			path1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			g0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			svg0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div0_nodes, "\n\n            ");

			svg1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "svg", { class: true, width: true, height: true, version: true, viewBox: true, xmlns: true, "xmlns:cc": true, "xmlns:dc": true, "xmlns:osb": true, "xmlns:rdf": true }, true);
			var svg1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(svg1);

			g1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg1_nodes, "g", { transform: true }, true);
			var g1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g1);

			path2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(g1_nodes, "path", { transform: true, d: true, fill: true, stroke: true, "stroke-width": true }, true);
			var path2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(path2);

			path2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			g1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			svg1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div0_nodes, "\n\n            ");

			svg2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "svg", { class: true, width: true, height: true, version: true, viewBox: true, xmlns: true, "xmlns:cc": true, "xmlns:dc": true, "xmlns:osb": true, "xmlns:rdf": true }, true);
			var svg2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(svg2);

			path3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg2_nodes, "path", { class: true, transform: true, d: true, fill: true, stroke: true, "stroke-width": true }, true);
			var path3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(path3);

			path3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			svg2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n        ");

			h21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "H2", { class: true }, false);
			var h21_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h21);

			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h21_nodes, "Nebula Web Development");
			h21_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			a0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			h22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "H2", { style: true, class: true }, false);
			var h22_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h22);

			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h22_nodes, "OR..");
			h22_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "A", { href: true, class: true }, false);
			var a1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a1);

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a1_nodes, "DIV", { class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			h23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "H2", { class: true }, false);
			var h23_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h23);

			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h23_nodes, "Joystick Nebula Gaming");
			h23_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			a1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(h1, "class", "svelte-t62ywt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 94, 0, 2291);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(h20, "class", "svelte-t62ywt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h20, file, 95, 0, 2309);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p, "class", "svelte-t62ywt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 96, 0, 2360);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path0, "d", "m185.03 147.03c0.29362 28.491-17.677 55.422-42.969 67.929-30.732 16.052-71.107 11.16-96.601-12.53-20.34-18.105-29.779-47.749-22.423-74.131 7.5005-29.208 33.643-51.543 62.962-56.943 32.155-6.6565 68.021 6.741 86.315 34.375 8.1843 12.119 12.747 26.66 12.716 41.3z");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path0, "fill", "none");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path0, "stroke-width", "1.8428");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(path0, file, 114, 20, 3114);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path1, "d", "m63.5 88.446c0.32868 8.4746-9.0805 15.209-16.996 12.164-8.1276-2.4222-11.467-13.5-6.0327-20.011 4.9141-6.9121 16.477-6.5003 20.887 0.74378 1.3908 2.0894 2.1456 4.5929 2.1413 7.1029z");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path1, "stroke-width", "3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(path1, file, 118, 20, 3515);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(g0, "transform", "matrix(-.60424 0 0 -.6379 164.55 240.83)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(g0, "stroke", "#000");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g0, file, 111, 16, 2983);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "class", "ring svelte-t62ywt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "width", "80px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "height", "80px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "version", "1.1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "viewBox", "0 0 210 297");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "xmlns", "http://www.w3.org/2000/svg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "xmlns:cc", "http://creativecommons.org/ns#");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "xmlns:dc", "http://purl.org/dc/elements/1.1/");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "xmlns:osb", "http://www.openswatchbook.org/uri/2009/osb");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg0, "xmlns:rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(svg0, file, 100, 12, 2493);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path2, "transform", "matrix(.35289 0 0 .33592 -83.215 -98.67)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path2, "d", "m526.81 501.29a232.99 230.14 0 0 0-118.69 32.295 36.417 38.256 0 0 1 7.6328 23.436 36.417 38.256 0 0 1-36.416 38.258 36.417 38.256 0 0 1-28.443-14.369 232.99 230.14 0 0 0-56.74 150.52 232.99 230.14 0 0 0 232.99 230.14 232.99 230.14 0 0 0 232.99-230.14 232.99 230.14 0 0 0-232.99-230.13 232.99 230.14 0 0 0-0.33594 0zm-175.92 79.619a232.99 230.14 0 0 1 57.227-47.324 36.417 38.256 0 0 0-28.783-14.82 36.417 38.256 0 0 0-36.418 38.256 36.417 38.256 0 0 0 7.9746 23.889z");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path2, "fill", "none");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path2, "stroke", "#000");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path2, "stroke-width", "5.3523");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(path2, file, 136, 20, 4395);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(g1, "transform", "matrix(.74976 0 0 .78763 62.391 77.716)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g1, file, 135, 16, 4319);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "class", "ring1 svelte-t62ywt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "width", "80px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "height", "80px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "version", "1.1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "viewBox", "0 0 210 297");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "xmlns", "http://www.w3.org/2000/svg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "xmlns:cc", "http://creativecommons.org/ns#");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "xmlns:dc", "http://purl.org/dc/elements/1.1/");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "xmlns:osb", "http://www.openswatchbook.org/uri/2009/osb");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg1, "xmlns:rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(svg1, file, 124, 12, 3828);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path3, "class", "logo-group1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path3, "transform", "scale(.26458)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path3, "d", "m387.94 263.53a310.76 292.19 0 0 0-158.12 41.004 48.571 48.571 0 0 1 10.18 29.754 48.571 48.571 0 0 1-48.572 48.572 48.571 48.571 0 0 1-37.936-18.24 310.76 292.19 0 0 0-75.68 191.1 310.76 292.19 0 0 0 310.76 292.19 310.76 292.19 0 0 0 310.76-292.19 310.76 292.19 0 0 0-310.76-292.19 310.76 292.19 0 0 0-0.62891 0z");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path3, "fill", "none");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path3, "stroke", "#000");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path3, "stroke-width", "6.965");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(path3, file, 156, 16, 5641);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg2, "class", "ring2 svelte-t62ywt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg2, "width", "80px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg2, "height", "80px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg2, "version", "1.1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg2, "viewBox", "0 0 210 297");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg2, "xmlns", "http://www.w3.org/2000/svg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg2, "xmlns:cc", "http://creativecommons.org/ns#");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg2, "xmlns:dc", "http://purl.org/dc/elements/1.1/");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg2, "xmlns:osb", "http://www.openswatchbook.org/uri/2009/osb");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg2, "xmlns:rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(svg2, file, 145, 12, 5150);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div0, "class", "container svelte-t62ywt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 99, 8, 2457);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(h21, "class", "svelte-t62ywt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h21, file, 165, 8, 6223);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div1, "class", "logo-container svelte-t62ywt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 98, 4, 2420);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a0, "href", "./dev");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a0, "class", "svelte-t62ywt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a0, file, 97, 0, 2399);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(h22, "text-align", "center");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(h22, "font-size", "40px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(h22, "margin", "40px 0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(h22, "class", "svelte-t62ywt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h22, file, 168, 0, 6271);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(h23, "class", "svelte-t62ywt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h23, file, 171, 8, 6402);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div2, "class", "logo-container svelte-t62ywt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 170, 4, 6365);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a1, "href", "./nebula");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a1, "class", "svelte-t62ywt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a1, file, 169, 0, 6341);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, h1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, h20, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h20, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t3, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, p, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t5, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, a0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a0, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, svg0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg0, g0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(g0, path0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(g0, path1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, svg1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg1, g1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(g1, path2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, svg2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg2, path3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, h21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h21, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t10, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, h22, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h22, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t12, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, a1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a1, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, h23);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h23, t13);
		},

		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(h1);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t1);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(h20);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t3);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(p);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t5);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(a0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t10);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(h22);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t12);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(a1);
			}
		}
	};
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-t62ywt-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, null, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJhN2VkZTBkYThiZDBjYzBkNzM0ZC9pbmRleC5pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbXSwic291cmNlUm9vdCI6IiJ9